export const DOWNLOAD_PASSPHRASE = 'DOWNLOAD_PASSPHRASE';
export const DOWNLOAD_PRIVATE_KEY = 'DOWNLOAD_PRIVATE_KEY';

export const VEO_ADD_PENDING_TRANSACTION = 'VEO_ADD_PENDING_TRANSACTION';
export const VEO_REMOVE_PENDING_TRANSACTION = 'VEO_REMOVE_PENDING_TRANSACTION';
export const VEO_UPDATE_HEADER = 'header';
